name: Deploy to GCP

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Set up Google Cloud CLI
        uses: GoogleCloudPlatform/github-actions@v0
        with:
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          project_id: global-calling-402520

      - name: Build Docker image
        run: docker build -t gcr.io/global-calling-402520/hexagonal-events:latest -f Dockerfile .
        
      - name: Configure docker
        run: gcloud auth configure-docker gcr.io

      - name: Push Docker image to Google Container Registry
        run: docker push gcr.io/global-calling-402520/hexagonal-events:latest

      - name: SSH into Compute Engine
        uses: google-github-actions/ssh-compute@v0
        with:
          instance_name: 'events-mentorship'
          zone: 'us-east1-b'
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            docker pull gcr.io/global-calling-402520/hexagonal-events:latest         
            cd /general/infra
            docker-compose up -d