name: Deploy to GCP

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Set up Google Cloud CLI
        uses: 'google-github-actions/auth@v0'
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}
          project_id: global-calling-402520

      - name: Build Docker image
        run: docker build -t gcr.io/global-calling-402520/hexagonal-events:latest -f Dockerfile .
        
      - name: Configure docker
        run: gcloud auth configure-docker gcr.io

      - name: Push Docker image to Google Container Registry
        run: docker push gcr.io/global-calling-402520/hexagonal-events:latest

      - name: 'compute-ssh'
        id: 'compute-ssh'
        uses: google-github-actions/ssh-compute@v0
        with:
          instance_name: 'events-mentorship'
          zone: 'us-east1-b'
          user: yuri_simoes
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
          command: |
            gcloud auth configure-docker
            docker pull gcr.io/global-calling-402520/hexagonal-events:latest
            cd /home/yuri_simoes/general/infra
            docker compose up -d
            docker image prune -a -f

      - name: 'test'
        run: |-
          echo '${{ steps.compute-ssh.outputs.stdout }}'
          echo '${{ steps.compute-ssh.outputs.stderr }}'
