name: Deploy to GCP

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Set up Google Cloud CLI
        uses: GoogleCloudPlatform/github-actions/setup-gcloud@v0
        with:
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          project_id: global-calling-402520

      - name: Build and push Docker image
        run: |
          docker build -t gcr.io/global-calling-402520/hexagonal-events:latest ../Dockerfile
          docker push gcr.io/global-calling-402520/hexagonal-events:latest

      - name: SSH into Compute Engine
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST_IP }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            # Pull the Docker image
            docker pull gcr.io/global-calling-402520/hexagonal-events:latest
            
            # Navigate to the directory where your Docker Compose file is located
            cd /general/infra
            
            # Start the Docker Compose stack
            docker-compose up -d